name: tsbs-test
on:
  pull_request:
    branches:
       - main
jobs:
  tsbs-test:
    name: tsbs-test
    env:
      DB_URL: ${{ secrets.PERFORMANCE_DB }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pwd
          git status
          git fetch
          sudo apt install tree
          cd ~
          tree -d
      - run: sudo cat /proc/cpuinfo
      - run: sudo cat /proc/meminfo
      - run: |
          sudo apt update
          sudo apt upgrade
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt update
          sudo pip install psycopg2
          sudo pip install pandas
          sudo pip install matplotlib
          sudo pip install numpy
          sudo pip install jq
          sudo apt install libssl-dev libkrb5-dev cmake make
          sudo apt install postgresql-14 postgresql-server-dev-14
          git fetch --all --tags
          echo y | ./bootstrap -DCMAKE_BUILD_TYPE=Debug -DASSERTIONS=ON
          cd build
          make
          sudo make install
          sudo sh -c "echo 'deb [signed-by=/usr/share/keyrings/timescale.keyring] https://packagecloud.io/timescale/timescaledb/ubuntu/ $(lsb_release -c -s) main' > /etc/apt/sources.list.d/timescaledb.list"
          wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/timescale.keyring
          sudo apt-get update
          sudo apt install timescaledb-tools
          sudo timescaledb-tune --quiet --yes
          sudo service postgresql start
      - run: sudo -u postgres psql --command "ALTER USER postgres PASSWORD 'postgres';"
      - run: sudo -u postgres psql postgres://postgres:postgres@localhost:5432/postgres --command 'select version();'
      - run: sudo service postgresql restart
      - run: sudo -u postgres psql --command 'create extension timescaledb;'
      - run: sudo -u postgres psql --command '\dx'
      - run: sudo apt install net-tools
      - run: sudo netstat -lntp
      - run: sudo cat /etc/postgresql/14/main/pg_hba.conf
      - run: sudo -u postgres psql --command '\l'
      - run: |
          sudo apt install golang make -y
          git clone https://github.com/timescale/tsbs.git
          cd tsbs
          make
      - run: tsbs/bin/tsbs_generate_data --use-case="iot" --seed=123 --scale=4000     --timestamp-start="2016-01-01T00:00:00Z"      --timestamp-end="2016-01-02T01:33:00Z"    --log-interval="20s" --format="timescaledb"     > /tmp/timescaledb-data
      - run: tsbs/bin/tsbs_load load timescaledb --config scripts/tsbs-loader.yaml | tee ~/tsbsloadoutput.txt
      - run: rm /tmp/timescaledb-data
      - run: cat ~/tsbsloadoutput.txt
      - run: tsbs/bin/tsbs_generate_queries --use-case="iot" --seed=123 --scale=4000     --timestamp-start="2016-01-01T00:00:00Z"     --timestamp-end="2016-01-02T00:00:00Z"    --queries=200 --query-type="breakdown-frequency" --format="timescaledb"     | gzip > /tmp/timescaledb-queries-breakdown-frequency.gz
      - run: cat /tmp/timescaledb-queries-breakdown-frequency.gz | gunzip | tsbs/bin/tsbs_run_queries_timescaledb --workers=8 --postgres="host=localhost user=postgres password=postgres" | tee ~/tsbsqueryoutput.txt
      - run: cat ~/tsbsqueryoutput.txt
      - name: Run test load json db
        env:
          DB_URL: ${{ secrets.PERFORMANCE_DB }}
        run: |
          export CPU_INFO=`cat /proc/cpuinfo | grep "model name" | uniq -c | awk -F":" '{gsub(/^[ \t]+/,"",$1);gsub(/^[ \t]+/,"",$2);gsub(/[\t ]+$/,"",$1); gsub(/[ \t]+$/,"",$2); gsub(/ model name/,"",$1) ; print "{\"count\"\:"$1",\"type\"\:\""$2"\"}"}'`
          echo $CPU_INFO
          export DRM_GIT_REPO="`git config --get remote.origin.url`"
          export DRM_GIT_COMMIT="`git rev-parse HEAD`"
          export DRM_GIT_BRANCH="`git rev-parse --abbrev-ref HEAD`"
          export DRM_GIT_BRANCH="`git status | head -1`"
          cd ~; python ~/work/timescaledb/timescaledb/scripts/tsbs-results-load.py
          cd ~; python ~/work/timescaledb/timescaledb/scripts/tsbs-results-query.py
